services:
  capstone-postgres-db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  capstone-backend:
    image: ${BACKEND_IMAGE}
    restart: unless-stopped
    depends_on:
      - capstone-postgres-db
    environment:
      PORT: 3000
      PG_USER: ${POSTGRES_USER}
      PG_PASSWORD: ${POSTGRES_PASSWORD}
      PG_DATABASE: ${POSTGRES_DB}
      PG_HOST: capstone-postgres-db
      PG_PORT: 5432
    ports:
      - "3000:3000"

  capstone-frontend:
    image: ${FRONTEND_IMAGE}
    restart: unless-stopped
    depends_on:
      - capstone-backend
    ports:
      - "8080:80"

  proxy:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - capstone-backend
      - capstone-frontend

volumes:
  postgres_data:
